// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
)

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at FROM account WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at FROM account WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByWebauthnUserHandle = `-- name: GetAccountByWebauthnUserHandle :one
SELECT id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at FROM account WHERE webauthn_user_handle = $1
`

func (q *Queries) GetAccountByWebauthnUserHandle(ctx context.Context, webauthnUserHandle []byte) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByWebauthnUserHandle, webauthnUserHandle)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasAnyActiveAdmin = `-- name: HasAnyActiveAdmin :one
SELECT EXISTS(SELECT 1 FROM account WHERE role = 'admin' AND NOT disabled) AS has_admin
`

func (q *Queries) HasAnyActiveAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyActiveAdmin)
	var has_admin bool
	err := row.Scan(&has_admin)
	return has_admin, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO account (
  username, display_name, webauthn_user_handle, role,
  can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces,
  disabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at
`

type InsertAccountParams struct {
	Username            string `json:"username"`
	DisplayName         string `json:"displayName"`
	WebauthnUserHandle  []byte `json:"webauthnUserHandle"`
	Role                string `json:"role"`
	CanViewOwnUsage     bool   `json:"canViewOwnUsage"`
	CanManageOwnApiKeys bool   `json:"canManageOwnApiKeys"`
	CanViewModels       bool   `json:"canViewModels"`
	CanViewOwnTraces    bool   `json:"canViewOwnTraces"`
	Disabled            bool   `json:"disabled"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.Username,
		arg.DisplayName,
		arg.WebauthnUserHandle,
		arg.Role,
		arg.CanViewOwnUsage,
		arg.CanManageOwnApiKeys,
		arg.CanViewModels,
		arg.CanViewOwnTraces,
		arg.Disabled,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
