// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdminsForUpdate = `-- name: CountActiveAdminsForUpdate :one
SELECT COUNT(*) FROM account WHERE role = 'admin' AND NOT disabled FOR UPDATE
`

func (q *Queries) CountActiveAdminsForUpdate(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdminsForUpdate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccountByID = `-- name: DeleteAccountByID :exec
DELETE FROM account WHERE id = $1
`

func (q *Queries) DeleteAccountByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAccountByID, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at, can_manage_own_projects FROM account WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int32) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanManageOwnProjects,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at, can_manage_own_projects FROM account WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanManageOwnProjects,
	)
	return i, err
}

const getAccountByWebauthnUserHandle = `-- name: GetAccountByWebauthnUserHandle :one
SELECT id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at, can_manage_own_projects FROM account WHERE webauthn_user_handle = $1
`

func (q *Queries) GetAccountByWebauthnUserHandle(ctx context.Context, webauthnUserHandle []byte) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByWebauthnUserHandle, webauthnUserHandle)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanManageOwnProjects,
	)
	return i, err
}

const hasAnyActiveAdmin = `-- name: HasAnyActiveAdmin :one
SELECT EXISTS(SELECT 1 FROM account WHERE role = 'admin' AND NOT disabled) AS has_admin
`

func (q *Queries) HasAnyActiveAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAnyActiveAdmin)
	var has_admin bool
	err := row.Scan(&has_admin)
	return has_admin, err
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO account (
  username, display_name, webauthn_user_handle, role,
  can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces,
  disabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at, can_manage_own_projects
`

type InsertAccountParams struct {
	Username            string `json:"username"`
	DisplayName         string `json:"displayName"`
	WebauthnUserHandle  []byte `json:"webauthnUserHandle"`
	Role                string `json:"role"`
	CanViewOwnUsage     bool   `json:"canViewOwnUsage"`
	CanManageOwnApiKeys bool   `json:"canManageOwnApiKeys"`
	CanViewModels       bool   `json:"canViewModels"`
	CanViewOwnTraces    bool   `json:"canViewOwnTraces"`
	Disabled            bool   `json:"disabled"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.Username,
		arg.DisplayName,
		arg.WebauthnUserHandle,
		arg.Role,
		arg.CanViewOwnUsage,
		arg.CanManageOwnApiKeys,
		arg.CanViewModels,
		arg.CanViewOwnTraces,
		arg.Disabled,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanManageOwnProjects,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
  a.id, a.username, a.display_name, a.webauthn_user_handle, a.role, a.can_view_own_usage, a.can_manage_own_api_keys, a.can_view_models, a.can_view_own_traces, a.disabled, a.created_at, a.updated_at, a.can_manage_own_projects,
  (SELECT MAX(c.last_used_at) FROM webauthn_credential c WHERE c.account_id = a.id)::timestamptz AS last_sign_in_at
FROM account a
ORDER BY a.created_at ASC, a.id ASC
`

type ListAccountsRow struct {
	ID                   int32              `json:"id"`
	Username             string             `json:"username"`
	DisplayName          string             `json:"displayName"`
	WebauthnUserHandle   []byte             `json:"webauthnUserHandle"`
	Role                 string             `json:"role"`
	CanViewOwnUsage      bool               `json:"canViewOwnUsage"`
	CanManageOwnApiKeys  bool               `json:"canManageOwnApiKeys"`
	CanViewModels        bool               `json:"canViewModels"`
	CanViewOwnTraces     bool               `json:"canViewOwnTraces"`
	Disabled             bool               `json:"disabled"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt            pgtype.Timestamptz `json:"updatedAt"`
	CanManageOwnProjects bool               `json:"canManageOwnProjects"`
	LastSignInAt         pgtype.Timestamptz `json:"lastSignInAt"`
}

func (q *Queries) ListAccounts(ctx context.Context) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.WebauthnUserHandle,
			&i.Role,
			&i.CanViewOwnUsage,
			&i.CanManageOwnApiKeys,
			&i.CanViewModels,
			&i.CanViewOwnTraces,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanManageOwnProjects,
			&i.LastSignInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE account SET
  display_name = $2, role = $3,
  can_view_own_usage = $4, can_manage_own_api_keys = $5,
  can_view_models = $6, can_view_own_traces = $7,
  disabled = $8, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, webauthn_user_handle, role, can_view_own_usage, can_manage_own_api_keys, can_view_models, can_view_own_traces, disabled, created_at, updated_at, can_manage_own_projects
`

type UpdateAccountParams struct {
	ID                  int32  `json:"id"`
	DisplayName         string `json:"displayName"`
	Role                string `json:"role"`
	CanViewOwnUsage     bool   `json:"canViewOwnUsage"`
	CanManageOwnApiKeys bool   `json:"canManageOwnApiKeys"`
	CanViewModels       bool   `json:"canViewModels"`
	CanViewOwnTraces    bool   `json:"canViewOwnTraces"`
	Disabled            bool   `json:"disabled"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.ID,
		arg.DisplayName,
		arg.Role,
		arg.CanViewOwnUsage,
		arg.CanManageOwnApiKeys,
		arg.CanViewModels,
		arg.CanViewOwnTraces,
		arg.Disabled,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.WebauthnUserHandle,
		&i.Role,
		&i.CanViewOwnUsage,
		&i.CanManageOwnApiKeys,
		&i.CanViewModels,
		&i.CanViewOwnTraces,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanManageOwnProjects,
	)
	return i, err
}
