// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEnrollment = `-- name: ConsumeEnrollment :one
UPDATE enrollment
SET consumed_at = now()
WHERE token = $1 AND consumed_at IS NULL
RETURNING token, intent, target_account_id, created_at, expires_at, consumed_at
`

// Atomic single-use consume. Returns the row only if it was unconsumed.
// Callers detect the "already consumed" branch via pgx.ErrNoRows.
func (q *Queries) ConsumeEnrollment(ctx context.Context, token string) (Enrollment, error) {
	row := q.db.QueryRow(ctx, consumeEnrollment, token)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getEnrollmentByToken = `-- name: GetEnrollmentByToken :one
SELECT token, intent, target_account_id, created_at, expires_at, consumed_at FROM enrollment WHERE token = $1
`

func (q *Queries) GetEnrollmentByToken(ctx context.Context, token string) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByToken, token)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertEnrollment = `-- name: InsertEnrollment :one
INSERT INTO enrollment (token, intent, target_account_id, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token, intent, target_account_id, created_at, expires_at, consumed_at
`

type InsertEnrollmentParams struct {
	Token           string             `json:"token"`
	Intent          string             `json:"intent"`
	TargetAccountID pgtype.Int4        `json:"targetAccountId"`
	ExpiresAt       pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, insertEnrollment,
		arg.Token,
		arg.Intent,
		arg.TargetAccountID,
		arg.ExpiresAt,
	)
	var i Enrollment
	err := row.Scan(
		&i.Token,
		&i.Intent,
		&i.TargetAccountID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
