// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM project WHERE id = $1 AND account_id = $2
`

type DeleteProjectParams struct {
	ID        int32 `json:"id"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByAccountAndName = `-- name: GetProjectByAccountAndName :one
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, account_id FROM project WHERE account_id = $1 AND name = $2 LIMIT 1
`

type GetProjectByAccountAndNameParams struct {
	AccountID int32  `json:"accountId"`
	Name      string `json:"name"`
}

func (q *Queries) GetProjectByAccountAndName(ctx context.Context, arg GetProjectByAccountAndNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByAccountAndName, arg.AccountID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const getProjectForAccount = `-- name: GetProjectForAccount :one
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, account_id FROM project WHERE id = $1 AND account_id = $2 LIMIT 1
`

type GetProjectForAccountParams struct {
	ID        int32 `json:"id"`
	AccountID int32 `json:"accountId"`
}

func (q *Queries) GetProjectForAccount(ctx context.Context, arg GetProjectForAccountParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForAccount, arg.ID, arg.AccountID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO project (account_id, name, paths) VALUES ($1, $2, $3) RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, account_id
`

type InsertProjectParams struct {
	AccountID int32  `json:"accountId"`
	Name      string `json:"name"`
	Paths     []byte `json:"paths"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject, arg.AccountID, arg.Name, arg.Paths)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const insertProjectIfNotExists = `-- name: InsertProjectIfNotExists :one
INSERT INTO project (account_id, name, paths)
VALUES ($1, $2, $3)
ON CONFLICT (account_id, name) DO NOTHING
RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, account_id
`

type InsertProjectIfNotExistsParams struct {
	AccountID int32  `json:"accountId"`
	Name      string `json:"name"`
	Paths     []byte `json:"paths"`
}

// Used by the gateway auto-create path. ON CONFLICT DO NOTHING means a
// concurrent insert by the same (account_id, name) leaves the prior row
// in place and RETURNING is empty; callers must follow up with
// GetProjectByAccountAndName to fetch the existing row.
func (q *Queries) InsertProjectIfNotExists(ctx context.Context, arg InsertProjectIfNotExistsParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProjectIfNotExists, arg.AccountID, arg.Name, arg.Paths)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const listProjectPaths = `-- name: ListProjectPaths :many
SELECT id AS project_id, account_id, jsonb_array_elements_text(paths) AS path
FROM project
WHERE jsonb_array_length(paths) > 0
`

type ListProjectPathsRow struct {
	ProjectID int32  `json:"projectId"`
	AccountID int32  `json:"accountId"`
	Path      string `json:"path"`
}

func (q *Queries) ListProjectPaths(ctx context.Context) ([]ListProjectPathsRow, error) {
	rows, err := q.db.Query(ctx, listProjectPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectPathsRow
	for rows.Next() {
		var i ListProjectPathsRow
		if err := rows.Scan(&i.ProjectID, &i.AccountID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByAccount = `-- name: ListProjectsByAccount :many
SELECT id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, account_id FROM project WHERE account_id = $1 ORDER BY name ASC
`

func (q *Queries) ListProjectsByAccount(ctx context.Context, accountID int32) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Paths,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE project SET name = $2, paths = $3, updated_at = now()
WHERE id = $1 AND account_id = $4
RETURNING id, name, paths, first_seen_at, last_seen_at, created_at, updated_at, account_id
`

type UpdateProjectParams struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Paths     []byte `json:"paths"`
	AccountID int32  `json:"accountId"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Paths,
		arg.AccountID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Paths,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
	)
	return i, err
}

const upsertProjectSeen = `-- name: UpsertProjectSeen :exec
UPDATE project
SET first_seen_at = LEAST(COALESCE(first_seen_at, $2::timestamp), $2::timestamp),
    last_seen_at  = GREATEST(COALESCE(last_seen_at,  $2::timestamp), $2::timestamp),
    updated_at    = now()
WHERE id = $1
`

type UpsertProjectSeenParams struct {
	ID     int32            `json:"id"`
	SeenAt pgtype.Timestamp `json:"seenAt"`
}

func (q *Queries) UpsertProjectSeen(ctx context.Context, arg UpsertProjectSeenParams) error {
	_, err := q.db.Exec(ctx, upsertProjectSeen, arg.ID, arg.SeenAt)
	return err
}
