// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BackfillTrace(ctx context.Context, arg BackfillTraceParams) error
	// Atomic single-use consume. Returns the row only if it was unconsumed and unexpired.
	// Callers detect any "not consumable" branch via pgx.ErrNoRows.
	ConsumeEnrollment(ctx context.Context, token string) (Enrollment, error)
	CountActiveAdminsForUpdate(ctx context.Context) (int64, error)
	CountCredentialsByAccount(ctx context.Context, accountID int32) (int64, error)
	CountTraces(ctx context.Context, arg CountTracesParams) (int64, error)
	CountTracesFiltered(ctx context.Context, arg CountTracesFilteredParams) (int64, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	DeleteAccountByID(ctx context.Context, id int32) error
	DeleteAllCredentialsForAccount(ctx context.Context, accountID int32) error
	DeleteApiKey(ctx context.Context, id int32) error
	// Owner-scoped delete: zero rows affected means the id doesn't match an owned
	// credential; handlers map that to credential_not_found.
	DeleteCredentialByID(ctx context.Context, arg DeleteCredentialByIDParams) (int64, error)
	DeleteEndpoint(ctx context.Context, path string) error
	DeleteExchangeRate(ctx context.Context, code string) error
	DeleteModel(ctx context.Context, name string) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error)
	DeleteProvider(ctx context.Context, id int32) error
	DeleteProviderEndpoint(ctx context.Context, arg DeleteProviderEndpointParams) error
	DeleteScript(ctx context.Context, id string) error
	GetAccountByID(ctx context.Context, id int32) (Account, error)
	GetAccountByUsername(ctx context.Context, username string) (Account, error)
	GetAccountByWebauthnUserHandle(ctx context.Context, webauthnUserHandle []byte) (Account, error)
	GetApiKey(ctx context.Context, id int32) (ApiKey, error)
	GetApiKeyByKey(ctx context.Context, key string) (ApiKey, error)
	GetApiKeyOwnedBy(ctx context.Context, arg GetApiKeyOwnedByParams) (ApiKey, error)
	GetCredentialByCredentialID(ctx context.Context, credentialID []byte) (WebauthnCredential, error)
	GetEndpointByPath(ctx context.Context, path string) (Endpoint, error)
	GetEndpoints(ctx context.Context) ([]Endpoint, error)
	GetEnrollmentByToken(ctx context.Context, token string) (Enrollment, error)
	GetExchangeRateByCode(ctx context.Context, code string) (ExchangeRate, error)
	GetExchangeRates(ctx context.Context) ([]ExchangeRate, error)
	GetFirstEndpointByType(ctx context.Context, endpointType int32) (Endpoint, error)
	GetModelByName(ctx context.Context, name string) (Model, error)
	GetModels(ctx context.Context) ([]Model, error)
	GetOverviewTokenBreakdown(ctx context.Context, arg GetOverviewTokenBreakdownParams) (GetOverviewTokenBreakdownRow, error)
	GetOverviewTotals(ctx context.Context, arg GetOverviewTotalsParams) (GetOverviewTotalsRow, error)
	GetProjectByAccountAndName(ctx context.Context, arg GetProjectByAccountAndNameParams) (Project, error)
	GetProjectForAccount(ctx context.Context, arg GetProjectForAccountParams) (Project, error)
	GetProviderByID(ctx context.Context, id int32) (Provider, error)
	GetProviderEndpoint(ctx context.Context, arg GetProviderEndpointParams) (ProviderEndpoint, error)
	GetProviders(ctx context.Context) ([]Provider, error)
	// Sister query to GetProvidersByEndpointAndModel for "no-model" endpoints
	// (endpoint.model_path = ''). Returns every non-disabled provider bound to the
	// given endpoint_path, with model-related columns flattened to constants so the
	// consuming Go code can treat both shapes uniformly.
	GetProvidersByEndpoint(ctx context.Context, endpointPath string) ([]GetProvidersByEndpointRow, error)
	GetProvidersByEndpointAndModel(ctx context.Context, arg GetProvidersByEndpointAndModelParams) ([]GetProvidersByEndpointAndModelRow, error)
	// Sister query to GetProvidersByEndpointAndModel that selects across a SET of
	// endpoint types instead of a single endpoint path. The unified gateway
	// routes (/v1/messages, /v1/responses, /v1/chat/completions, and the two
	// Gemini variants) compute the type set from (source format, stream flag)
	// and call this. Returns the same column shape as the path-based query plus
	// e.endpoint_type so the handler can pick the right transformer per row.
	GetProvidersByEndpointTypesAndModel(ctx context.Context, arg GetProvidersByEndpointTypesAndModelParams) ([]GetProvidersByEndpointTypesAndModelRow, error)
	GetRequest(ctx context.Context, arg GetRequestParams) (Request, error)
	GetRequestOwnedBy(ctx context.Context, arg GetRequestOwnedByParams) (Request, error)
	GetScript(ctx context.Context, id string) (Script, error)
	HasAnyActiveAdmin(ctx context.Context) (bool, error)
	InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error)
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (ApiKey, error)
	InsertCredential(ctx context.Context, arg InsertCredentialParams) (WebauthnCredential, error)
	// template_username ($11) and template_display_name ($12) are always NULL
	// as of P5.03 — the invite flow no longer pre-populates username/displayName.
	InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) (Enrollment, error)
	InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error)
	// Used by the gateway auto-create path. ON CONFLICT DO NOTHING means a
	// concurrent insert by the same (account_id, name) leaves the prior row
	// in place and RETURNING is empty; callers must follow up with
	// GetProjectByAccountAndName to fetch the existing row.
	InsertProjectIfNotExists(ctx context.Context, arg InsertProjectIfNotExistsParams) (Project, error)
	InsertRequest(ctx context.Context, arg InsertRequestParams) (pgtype.Timestamp, error)
	InsertScript(ctx context.Context, arg InsertScriptParams) (Script, error)
	ListAccounts(ctx context.Context) ([]ListAccountsRow, error)
	ListApiKeys(ctx context.Context) ([]ApiKey, error)
	ListApiKeysByAccount(ctx context.Context, accountID int32) ([]ApiKey, error)
	ListCredentialsByAccount(ctx context.Context, accountID int32) ([]WebauthnCredential, error)
	ListEnabledScripts(ctx context.Context) ([]Script, error)
	ListOverviewBreakdownCosts(ctx context.Context, arg ListOverviewBreakdownCostsParams) ([]ListOverviewBreakdownCostsRow, error)
	ListOverviewBreakdownTokens(ctx context.Context, arg ListOverviewBreakdownTokensParams) ([]ListOverviewBreakdownTokensRow, error)
	ListOverviewDistribution(ctx context.Context, arg ListOverviewDistributionParams) ([]ListOverviewDistributionRow, error)
	ListOverviewDistributionCosts(ctx context.Context, arg ListOverviewDistributionCostsParams) ([]ListOverviewDistributionCostsRow, error)
	ListOverviewSeriesMetrics(ctx context.Context, arg ListOverviewSeriesMetricsParams) ([]ListOverviewSeriesMetricsRow, error)
	ListOverviewSeriesTraces(ctx context.Context, arg ListOverviewSeriesTracesParams) ([]ListOverviewSeriesTracesRow, error)
	ListOverviewSpeedSeries(ctx context.Context, arg ListOverviewSpeedSeriesParams) ([]ListOverviewSpeedSeriesRow, error)
	ListOverviewTraceCountsByDimension(ctx context.Context, arg ListOverviewTraceCountsByDimensionParams) ([]ListOverviewTraceCountsByDimensionRow, error)
	ListPendingInvitations(ctx context.Context) ([]Enrollment, error)
	ListProjectPaths(ctx context.Context) ([]ListProjectPathsRow, error)
	ListProjectsByAccount(ctx context.Context, accountID int32) ([]Project, error)
	ListProviderEndpoints(ctx context.Context, providerID pgtype.Int4) ([]ProviderEndpoint, error)
	ListRequestSpansOwnedBy(ctx context.Context, arg ListRequestSpansOwnedByParams) ([]ListRequestSpansOwnedByRow, error)
	ListRequestTraces(ctx context.Context, arg ListRequestTracesParams) ([]ListRequestTracesRow, error)
	ListRequestTracesByAccount(ctx context.Context, arg ListRequestTracesByAccountParams) ([]ListRequestTracesByAccountRow, error)
	ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error)
	ListRequestsByAccount(ctx context.Context, arg ListRequestsByAccountParams) ([]ListRequestsByAccountRow, error)
	ListRequestsBySpan(ctx context.Context, arg ListRequestsBySpanParams) ([]ListRequestsBySpanRow, error)
	ListScripts(ctx context.Context) ([]Script, error)
	ListTraceBackfillCandidates(ctx context.Context) ([]ListTraceBackfillCandidatesRow, error)
	// Same DB effect as ConsumeEnrollment but intent-restricted to 'invite' so an
	// admin cannot accidentally use this to mark a bootstrap/reset token consumed.
	// Returns the row only if it was unconsumed AND of intent=invite; otherwise
	// pgx.ErrNoRows surfaces and the handler maps to invitation_not_found.
	RevokeInvitation(ctx context.Context, token string) (Enrollment, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateApiKey(ctx context.Context, arg UpdateApiKeyParams) (ApiKey, error)
	UpdateCredentialUsage(ctx context.Context, arg UpdateCredentialUsageParams) error
	// Owner-scoped update: only the account's own credential row is updated.
	// Zero rows affected means the id doesn't match an owned credential; the
	// handler then surfaces credential_not_found.
	UpdateMyCredentialNickname(ctx context.Context, arg UpdateMyCredentialNicknameParams) (int64, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	// Backfills the meta request row's account_id after authentication completes,
	// mirroring UpdateRequestProjectID. Same lifecycle: meta InsertRequest fires
	// pre-auth so audit rows always land; this updates with the authenticated
	// owner once known.
	UpdateRequestAccountID(ctx context.Context, arg UpdateRequestAccountIDParams) error
	UpdateRequestMetrics(ctx context.Context, arg UpdateRequestMetricsParams) error
	UpdateRequestModel(ctx context.Context, arg UpdateRequestModelParams) error
	UpdateRequestOnComplete(ctx context.Context, arg UpdateRequestOnCompleteParams) error
	UpdateRequestOnHeader(ctx context.Context, arg UpdateRequestOnHeaderParams) error
	// Backfills the meta request row's project_id after authentication completes.
	// The meta InsertRequest fires before auth so audit rows always exist; the
	// account-scoped project resolution then writes the matched id here.
	UpdateRequestProjectID(ctx context.Context, arg UpdateRequestProjectIDParams) error
	UpdateScript(ctx context.Context, arg UpdateScriptParams) (Script, error)
	UpsertEndpoint(ctx context.Context, arg UpsertEndpointParams) (Endpoint, error)
	UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) (ExchangeRate, error)
	UpsertModel(ctx context.Context, arg UpsertModelParams) (Model, error)
	UpsertProjectSeen(ctx context.Context, arg UpsertProjectSeenParams) error
	UpsertProviderEndpoint(ctx context.Context, arg UpsertProviderEndpointParams) (ProviderEndpoint, error)
	UpsertTrace(ctx context.Context, arg UpsertTraceParams) (UpsertTraceRow, error)
}

var _ Querier = (*Queries)(nil)
