// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequest = `-- name: GetRequest :one
SELECT id, span_id, parent_span_id, provider_id, endpoint_path, api_key_id, model, input_tokens, cache_read_tokens, output_tokens, cache_write_tokens, status_code, error_message, ttft_ms, time_spent_ms, created_at, type, status, upstream_model, model_cost, model_cost_currency, user_message_preview, cache_write_1h_tokens, project_id, account_id FROM request WHERE id = $1 AND created_at = $2::timestamp
`

type GetRequestParams struct {
	ID          string           `json:"id"`
	IDCreatedAt pgtype.Timestamp `json:"idCreatedAt"`
}

func (q *Queries) GetRequest(ctx context.Context, arg GetRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, arg.ID, arg.IDCreatedAt)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.ProviderID,
		&i.EndpointPath,
		&i.ApiKeyID,
		&i.Model,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.OutputTokens,
		&i.CacheWriteTokens,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.TtftMs,
		&i.TimeSpentMs,
		&i.CreatedAt,
		&i.Type,
		&i.Status,
		&i.UpstreamModel,
		&i.ModelCost,
		&i.ModelCostCurrency,
		&i.UserMessagePreview,
		&i.CacheWrite1hTokens,
		&i.ProjectID,
		&i.AccountID,
	)
	return i, err
}

const getRequestOwnedBy = `-- name: GetRequestOwnedBy :one
SELECT r.id, r.span_id, r.parent_span_id, r.provider_id, r.endpoint_path, r.api_key_id, r.model, r.input_tokens, r.cache_read_tokens, r.output_tokens, r.cache_write_tokens, r.status_code, r.error_message, r.ttft_ms, r.time_spent_ms, r.created_at, r.type, r.status, r.upstream_model, r.model_cost, r.model_cost_currency, r.user_message_preview, r.cache_write_1h_tokens, r.project_id, r.account_id FROM request r
JOIN api_key k ON k.id = r.api_key_id
WHERE r.id = $1
  AND r.created_at = $3::timestamp
  AND k.account_id = $2
`

type GetRequestOwnedByParams struct {
	ID          string           `json:"id"`
	AccountID   int32            `json:"accountId"`
	IDCreatedAt pgtype.Timestamp `json:"idCreatedAt"`
}

func (q *Queries) GetRequestOwnedBy(ctx context.Context, arg GetRequestOwnedByParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestOwnedBy, arg.ID, arg.AccountID, arg.IDCreatedAt)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.SpanID,
		&i.ParentSpanID,
		&i.ProviderID,
		&i.EndpointPath,
		&i.ApiKeyID,
		&i.Model,
		&i.InputTokens,
		&i.CacheReadTokens,
		&i.OutputTokens,
		&i.CacheWriteTokens,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.TtftMs,
		&i.TimeSpentMs,
		&i.CreatedAt,
		&i.Type,
		&i.Status,
		&i.UpstreamModel,
		&i.ModelCost,
		&i.ModelCostCurrency,
		&i.UserMessagePreview,
		&i.CacheWrite1hTokens,
		&i.ProjectID,
		&i.AccountID,
	)
	return i, err
}

const listRequestSpansOwnedBy = `-- name: ListRequestSpansOwnedBy :many
WITH anchor AS (
  SELECT request.span_id
  FROM request
  JOIN api_key k ON k.id = request.api_key_id
  WHERE request.id = $1::text
    AND request.created_at = $2::timestamp
    AND k.account_id = $3::int
)
SELECT r.id, r.span_id, r.parent_span_id, r.type, r.status, r.provider_id, r.endpoint_path,
       r.api_key_id, r.model, r.upstream_model, r.input_tokens, r.cache_read_tokens, r.output_tokens,
       r.cache_write_tokens, r.cache_write_1h_tokens, r.status_code, r.error_message, r.ttft_ms, r.time_spent_ms,
       r.created_at,
       r.model_cost, r.model_cost_currency,
       r.user_message_preview, r.project_id
FROM request r, anchor
WHERE r.span_id = anchor.span_id
ORDER BY r.created_at ASC, r.id ASC
`

type ListRequestSpansOwnedByParams struct {
	ID          string           `json:"id"`
	IDCreatedAt pgtype.Timestamp `json:"idCreatedAt"`
	AccountID   int32            `json:"accountId"`
}

type ListRequestSpansOwnedByRow struct {
	ID                 string           `json:"id"`
	SpanID             pgtype.Text      `json:"spanId"`
	ParentSpanID       pgtype.Text      `json:"parentSpanId"`
	Type               int32            `json:"type"`
	Status             int32            `json:"status"`
	ProviderID         pgtype.Int4      `json:"providerId"`
	EndpointPath       pgtype.Text      `json:"endpointPath"`
	ApiKeyID           pgtype.Int4      `json:"apiKeyId"`
	Model              pgtype.Text      `json:"model"`
	UpstreamModel      pgtype.Text      `json:"upstreamModel"`
	InputTokens        pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens    pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens       pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens   pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens pgtype.Int4      `json:"cacheWrite1hTokens"`
	StatusCode         pgtype.Int4      `json:"statusCode"`
	ErrorMessage       pgtype.Text      `json:"errorMessage"`
	TtftMs             pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs        pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	ModelCost          pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency  pgtype.Text      `json:"modelCostCurrency"`
	UserMessagePreview pgtype.Text      `json:"userMessagePreview"`
	ProjectID          pgtype.Int4      `json:"projectId"`
}

func (q *Queries) ListRequestSpansOwnedBy(ctx context.Context, arg ListRequestSpansOwnedByParams) ([]ListRequestSpansOwnedByRow, error) {
	rows, err := q.db.Query(ctx, listRequestSpansOwnedBy, arg.ID, arg.IDCreatedAt, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestSpansOwnedByRow
	for rows.Next() {
		var i ListRequestSpansOwnedByRow
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Type,
			&i.Status,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
			&i.ModelCost,
			&i.ModelCostCurrency,
			&i.UserMessagePreview,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestTraces = `-- name: ListRequestTraces :many
SELECT
  traces.id,
  traces.parent_span_id,
  COALESCE(metrics.meta_request_count, 0)::bigint AS meta_request_count,
  COALESCE(metrics.upstream_request_count, 0)::bigint AS upstream_request_count,
  COALESCE(metrics.total_tokens, 0)::bigint AS total_tokens,
  COALESCE(metrics.input_tokens, 0)::bigint AS input_tokens,
  COALESCE(metrics.cache_read_tokens, 0)::bigint AS cache_read_tokens,
  COALESCE(metrics.output_tokens, 0)::bigint AS output_tokens,
  COALESCE(metrics.cache_write_tokens, 0)::bigint AS cache_write_tokens,
  COALESCE(metrics.cache_write_1h_tokens, 0)::bigint AS cache_write_1h_tokens,
  COALESCE(model_costs.costs, '[]'::jsonb)::jsonb AS model_costs,
  traces.first_request_at,
  traces.last_request_at,
  preview.user_message_preview,
  trace_project.project_id AS project_id
FROM traces
LEFT JOIN LATERAL (
  SELECT
    COUNT(*) FILTER (WHERE type = 0)::bigint AS meta_request_count,
    COUNT(*) FILTER (WHERE type = 1)::bigint AS upstream_request_count,
    COALESCE(SUM(
      COALESCE(input_tokens, 0)
      + COALESCE(cache_read_tokens, 0)
      + COALESCE(output_tokens, 0)
      + COALESCE(cache_write_tokens, 0)
      + COALESCE(cache_write_1h_tokens, 0)
    ) FILTER (WHERE type = 1), 0)::bigint AS total_tokens,
    COALESCE(SUM(COALESCE(input_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS input_tokens,
    COALESCE(SUM(COALESCE(cache_read_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_read_tokens,
    COALESCE(SUM(COALESCE(output_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS output_tokens,
    COALESCE(SUM(COALESCE(cache_write_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_write_tokens,
    COALESCE(SUM(COALESCE(cache_write_1h_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_write_1h_tokens
  FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
) metrics ON true
LEFT JOIN LATERAL (
  SELECT jsonb_agg(
    jsonb_build_object('currency', grouped.currency, 'amount', grouped.amount)
    ORDER BY grouped.currency
  ) AS costs
  FROM (
    SELECT model_cost_currency AS currency, SUM(model_cost)::float8 AS amount
    FROM request
    WHERE parent_span_id = traces.parent_span_id
      AND created_at >= traces.first_request_at
      AND created_at <= traces.last_request_at
      AND type = 1
      AND model_cost IS NOT NULL
      AND model_cost_currency IS NOT NULL
    GROUP BY model_cost_currency
  ) grouped
) model_costs ON true
LEFT JOIN LATERAL (
  SELECT user_message_preview
  FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
    AND type = 0
    AND user_message_preview IS NOT NULL
  ORDER BY created_at DESC, id DESC
  LIMIT 1
) preview ON true
LEFT JOIN LATERAL (
  SELECT project_id
  FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
    AND type = 0
    AND project_id IS NOT NULL
  ORDER BY created_at DESC, id DESC
  LIMIT 1
) trace_project ON true
WHERE
  $1::timestamp IS NULL
  OR (traces.last_request_at, traces.id) < (
    $1::timestamp,
    $2::text
  )
ORDER BY traces.last_request_at DESC, traces.id DESC
LIMIT $3::int
`

type ListRequestTracesParams struct {
	CursorLastRequestAt pgtype.Timestamp `json:"cursorLastRequestAt"`
	CursorTraceID       pgtype.Text      `json:"cursorTraceId"`
	Limit               pgtype.Int4      `json:"limit"`
}

type ListRequestTracesRow struct {
	ID                   string           `json:"id"`
	ParentSpanID         string           `json:"parentSpanId"`
	MetaRequestCount     int64            `json:"metaRequestCount"`
	UpstreamRequestCount int64            `json:"upstreamRequestCount"`
	TotalTokens          int64            `json:"totalTokens"`
	InputTokens          int64            `json:"inputTokens"`
	CacheReadTokens      int64            `json:"cacheReadTokens"`
	OutputTokens         int64            `json:"outputTokens"`
	CacheWriteTokens     int64            `json:"cacheWriteTokens"`
	CacheWrite1hTokens   int64            `json:"cacheWrite1hTokens"`
	ModelCosts           []byte           `json:"modelCosts"`
	FirstRequestAt       pgtype.Timestamp `json:"firstRequestAt"`
	LastRequestAt        pgtype.Timestamp `json:"lastRequestAt"`
	UserMessagePreview   pgtype.Text      `json:"userMessagePreview"`
	ProjectID            pgtype.Int4      `json:"projectId"`
}

func (q *Queries) ListRequestTraces(ctx context.Context, arg ListRequestTracesParams) ([]ListRequestTracesRow, error) {
	rows, err := q.db.Query(ctx, listRequestTraces, arg.CursorLastRequestAt, arg.CursorTraceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestTracesRow
	for rows.Next() {
		var i ListRequestTracesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSpanID,
			&i.MetaRequestCount,
			&i.UpstreamRequestCount,
			&i.TotalTokens,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.ModelCosts,
			&i.FirstRequestAt,
			&i.LastRequestAt,
			&i.UserMessagePreview,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestTracesByAccount = `-- name: ListRequestTracesByAccount :many
SELECT
  traces.id,
  traces.parent_span_id,
  COALESCE(metrics.meta_request_count, 0)::bigint AS meta_request_count,
  COALESCE(metrics.upstream_request_count, 0)::bigint AS upstream_request_count,
  COALESCE(metrics.total_tokens, 0)::bigint AS total_tokens,
  COALESCE(metrics.input_tokens, 0)::bigint AS input_tokens,
  COALESCE(metrics.cache_read_tokens, 0)::bigint AS cache_read_tokens,
  COALESCE(metrics.output_tokens, 0)::bigint AS output_tokens,
  COALESCE(metrics.cache_write_tokens, 0)::bigint AS cache_write_tokens,
  COALESCE(metrics.cache_write_1h_tokens, 0)::bigint AS cache_write_1h_tokens,
  COALESCE(model_costs.costs, '[]'::jsonb)::jsonb AS model_costs,
  traces.first_request_at,
  traces.last_request_at,
  preview.user_message_preview,
  trace_project.project_id AS project_id
FROM traces
LEFT JOIN LATERAL (
  SELECT
    COUNT(*) FILTER (WHERE type = 0)::bigint AS meta_request_count,
    COUNT(*) FILTER (WHERE type = 1)::bigint AS upstream_request_count,
    COALESCE(SUM(
      COALESCE(input_tokens, 0) + COALESCE(cache_read_tokens, 0) + COALESCE(output_tokens, 0)
      + COALESCE(cache_write_tokens, 0) + COALESCE(cache_write_1h_tokens, 0)
    ) FILTER (WHERE type = 1), 0)::bigint AS total_tokens,
    COALESCE(SUM(COALESCE(input_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS input_tokens,
    COALESCE(SUM(COALESCE(cache_read_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_read_tokens,
    COALESCE(SUM(COALESCE(output_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS output_tokens,
    COALESCE(SUM(COALESCE(cache_write_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_write_tokens,
    COALESCE(SUM(COALESCE(cache_write_1h_tokens, 0)) FILTER (WHERE type = 1), 0)::bigint AS cache_write_1h_tokens
  FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
) metrics ON true
LEFT JOIN LATERAL (
  SELECT jsonb_agg(
    jsonb_build_object('currency', grouped.currency, 'amount', grouped.amount)
    ORDER BY grouped.currency
  ) AS costs
  FROM (
    SELECT model_cost_currency AS currency, SUM(model_cost)::float8 AS amount
    FROM request
    WHERE parent_span_id = traces.parent_span_id
      AND created_at >= traces.first_request_at
      AND created_at <= traces.last_request_at
      AND type = 1
      AND model_cost IS NOT NULL
      AND model_cost_currency IS NOT NULL
    GROUP BY model_cost_currency
  ) grouped
) model_costs ON true
LEFT JOIN LATERAL (
  SELECT user_message_preview FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
    AND type = 0
    AND user_message_preview IS NOT NULL
  ORDER BY created_at DESC, id DESC
  LIMIT 1
) preview ON true
LEFT JOIN LATERAL (
  SELECT project_id FROM request
  WHERE parent_span_id = traces.parent_span_id
    AND created_at >= traces.first_request_at
    AND created_at <= traces.last_request_at
    AND type = 0
    AND project_id IS NOT NULL
  ORDER BY created_at DESC, id DESC
  LIMIT 1
) trace_project ON true
WHERE EXISTS (
  SELECT 1 FROM request r
  JOIN api_key k ON k.id = r.api_key_id
  WHERE r.parent_span_id = traces.parent_span_id
    AND r.created_at >= traces.first_request_at
    AND r.created_at <= traces.last_request_at
    AND k.account_id = $1::int
)
AND (
  $2::timestamp IS NULL
  OR (traces.last_request_at, traces.id) < (
    $2::timestamp,
    $3::text
  )
)
ORDER BY traces.last_request_at DESC, traces.id DESC
LIMIT $4::int
`

type ListRequestTracesByAccountParams struct {
	AccountID           int32            `json:"accountId"`
	CursorLastRequestAt pgtype.Timestamp `json:"cursorLastRequestAt"`
	CursorTraceID       pgtype.Text      `json:"cursorTraceId"`
	Limit               pgtype.Int4      `json:"limit"`
}

type ListRequestTracesByAccountRow struct {
	ID                   string           `json:"id"`
	ParentSpanID         string           `json:"parentSpanId"`
	MetaRequestCount     int64            `json:"metaRequestCount"`
	UpstreamRequestCount int64            `json:"upstreamRequestCount"`
	TotalTokens          int64            `json:"totalTokens"`
	InputTokens          int64            `json:"inputTokens"`
	CacheReadTokens      int64            `json:"cacheReadTokens"`
	OutputTokens         int64            `json:"outputTokens"`
	CacheWriteTokens     int64            `json:"cacheWriteTokens"`
	CacheWrite1hTokens   int64            `json:"cacheWrite1hTokens"`
	ModelCosts           []byte           `json:"modelCosts"`
	FirstRequestAt       pgtype.Timestamp `json:"firstRequestAt"`
	LastRequestAt        pgtype.Timestamp `json:"lastRequestAt"`
	UserMessagePreview   pgtype.Text      `json:"userMessagePreview"`
	ProjectID            pgtype.Int4      `json:"projectId"`
}

func (q *Queries) ListRequestTracesByAccount(ctx context.Context, arg ListRequestTracesByAccountParams) ([]ListRequestTracesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listRequestTracesByAccount,
		arg.AccountID,
		arg.CursorLastRequestAt,
		arg.CursorTraceID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestTracesByAccountRow
	for rows.Next() {
		var i ListRequestTracesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentSpanID,
			&i.MetaRequestCount,
			&i.UpstreamRequestCount,
			&i.TotalTokens,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.ModelCosts,
			&i.FirstRequestAt,
			&i.LastRequestAt,
			&i.UserMessagePreview,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequests = `-- name: ListRequests :many
SELECT r.id, r.span_id, r.parent_span_id, r.type, r.status, r.provider_id, r.endpoint_path, r.api_key_id, r.model,
       r.upstream_model, r.input_tokens, r.cache_read_tokens, r.output_tokens, r.cache_write_tokens, r.cache_write_1h_tokens,
       r.status_code, r.error_message, r.ttft_ms, r.time_spent_ms, r.created_at,
       r.model_cost, r.model_cost_currency,
       r.user_message_preview, r.project_id
FROM request r
LEFT JOIN traces selected_trace ON selected_trace.id = $1::text
WHERE
  ($2::int IS NULL OR r.type = $2)
  AND ($3::int IS NULL OR r.provider_id = $3)
  AND ($4::text IS NULL OR r.endpoint_path = $4)
  AND ($5::text IS NULL OR r.model = $5)
  AND ($6::text IS NULL OR r.upstream_model = $6)
  AND ($7::int IS NULL OR r.project_id = $7)
  AND (
    $1::text IS NULL
    OR (
      r.parent_span_id = selected_trace.parent_span_id
      AND r.created_at >= selected_trace.first_request_at
      AND r.created_at <= selected_trace.last_request_at
    )
  )
  AND (
    $8::timestamp IS NULL
    OR (r.created_at, r.id) < ($8::timestamp, $9::text)
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $10::int
`

type ListRequestsParams struct {
	TraceID         pgtype.Text      `json:"traceId"`
	Type            pgtype.Int4      `json:"type"`
	ProviderID      pgtype.Int4      `json:"providerId"`
	EndpointPath    pgtype.Text      `json:"endpointPath"`
	Model           pgtype.Text      `json:"model"`
	UpstreamModel   pgtype.Text      `json:"upstreamModel"`
	ProjectID       pgtype.Int4      `json:"projectId"`
	CursorCreatedAt pgtype.Timestamp `json:"cursorCreatedAt"`
	CursorID        pgtype.Text      `json:"cursorId"`
	Limit           pgtype.Int4      `json:"limit"`
}

type ListRequestsRow struct {
	ID                 string           `json:"id"`
	SpanID             pgtype.Text      `json:"spanId"`
	ParentSpanID       pgtype.Text      `json:"parentSpanId"`
	Type               int32            `json:"type"`
	Status             int32            `json:"status"`
	ProviderID         pgtype.Int4      `json:"providerId"`
	EndpointPath       pgtype.Text      `json:"endpointPath"`
	ApiKeyID           pgtype.Int4      `json:"apiKeyId"`
	Model              pgtype.Text      `json:"model"`
	UpstreamModel      pgtype.Text      `json:"upstreamModel"`
	InputTokens        pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens    pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens       pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens   pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens pgtype.Int4      `json:"cacheWrite1hTokens"`
	StatusCode         pgtype.Int4      `json:"statusCode"`
	ErrorMessage       pgtype.Text      `json:"errorMessage"`
	TtftMs             pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs        pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	ModelCost          pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency  pgtype.Text      `json:"modelCostCurrency"`
	UserMessagePreview pgtype.Text      `json:"userMessagePreview"`
	ProjectID          pgtype.Int4      `json:"projectId"`
}

func (q *Queries) ListRequests(ctx context.Context, arg ListRequestsParams) ([]ListRequestsRow, error) {
	rows, err := q.db.Query(ctx, listRequests,
		arg.TraceID,
		arg.Type,
		arg.ProviderID,
		arg.EndpointPath,
		arg.Model,
		arg.UpstreamModel,
		arg.ProjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsRow
	for rows.Next() {
		var i ListRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Type,
			&i.Status,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
			&i.ModelCost,
			&i.ModelCostCurrency,
			&i.UserMessagePreview,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByAccount = `-- name: ListRequestsByAccount :many
SELECT r.id, r.span_id, r.parent_span_id, r.type, r.status, r.provider_id, r.endpoint_path, r.api_key_id, r.model,
       r.upstream_model, r.input_tokens, r.cache_read_tokens, r.output_tokens, r.cache_write_tokens, r.cache_write_1h_tokens,
       r.status_code, r.error_message, r.ttft_ms, r.time_spent_ms, r.created_at,
       r.model_cost, r.model_cost_currency,
       r.user_message_preview, r.project_id
FROM request r
LEFT JOIN traces selected_trace ON selected_trace.id = $1::text
WHERE r.account_id = $2::int
  AND ($3::int IS NULL OR r.type = $3)
  AND ($4::int IS NULL OR r.provider_id = $4)
  AND ($5::text IS NULL OR r.endpoint_path = $5)
  AND ($6::text IS NULL OR r.model = $6)
  AND ($7::text IS NULL OR r.upstream_model = $7)
  AND ($8::int IS NULL OR r.project_id = $8)
  AND (
    $1::text IS NULL
    OR (
      r.parent_span_id = selected_trace.parent_span_id
      AND r.created_at >= selected_trace.first_request_at
      AND r.created_at <= selected_trace.last_request_at
    )
  )
  AND (
    $9::timestamp IS NULL
    OR (r.created_at, r.id) < ($9::timestamp, $10::text)
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT $11::int
`

type ListRequestsByAccountParams struct {
	TraceID         pgtype.Text      `json:"traceId"`
	AccountID       int32            `json:"accountId"`
	Type            pgtype.Int4      `json:"type"`
	ProviderID      pgtype.Int4      `json:"providerId"`
	EndpointPath    pgtype.Text      `json:"endpointPath"`
	Model           pgtype.Text      `json:"model"`
	UpstreamModel   pgtype.Text      `json:"upstreamModel"`
	ProjectID       pgtype.Int4      `json:"projectId"`
	CursorCreatedAt pgtype.Timestamp `json:"cursorCreatedAt"`
	CursorID        pgtype.Text      `json:"cursorId"`
	Limit           pgtype.Int4      `json:"limit"`
}

type ListRequestsByAccountRow struct {
	ID                 string           `json:"id"`
	SpanID             pgtype.Text      `json:"spanId"`
	ParentSpanID       pgtype.Text      `json:"parentSpanId"`
	Type               int32            `json:"type"`
	Status             int32            `json:"status"`
	ProviderID         pgtype.Int4      `json:"providerId"`
	EndpointPath       pgtype.Text      `json:"endpointPath"`
	ApiKeyID           pgtype.Int4      `json:"apiKeyId"`
	Model              pgtype.Text      `json:"model"`
	UpstreamModel      pgtype.Text      `json:"upstreamModel"`
	InputTokens        pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens    pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens       pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens   pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens pgtype.Int4      `json:"cacheWrite1hTokens"`
	StatusCode         pgtype.Int4      `json:"statusCode"`
	ErrorMessage       pgtype.Text      `json:"errorMessage"`
	TtftMs             pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs        pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	ModelCost          pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency  pgtype.Text      `json:"modelCostCurrency"`
	UserMessagePreview pgtype.Text      `json:"userMessagePreview"`
	ProjectID          pgtype.Int4      `json:"projectId"`
}

// Scoped sibling of ListRequests. Same filter shape, plus a mandatory
// account_id predicate. Uses request.account_id (denormalized in migration
// 030) instead of joining api_key, so history survives api_key/account
// deletion.
func (q *Queries) ListRequestsByAccount(ctx context.Context, arg ListRequestsByAccountParams) ([]ListRequestsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByAccount,
		arg.TraceID,
		arg.AccountID,
		arg.Type,
		arg.ProviderID,
		arg.EndpointPath,
		arg.Model,
		arg.UpstreamModel,
		arg.ProjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsByAccountRow
	for rows.Next() {
		var i ListRequestsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Type,
			&i.Status,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
			&i.ModelCost,
			&i.ModelCostCurrency,
			&i.UserMessagePreview,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsBySpan = `-- name: ListRequestsBySpan :many
WITH anchor AS (
  SELECT request.span_id
  FROM request
  WHERE request.id = $1::text
    AND request.created_at = $2::timestamp
)
SELECT r.id, r.span_id, r.parent_span_id, r.type, r.status, r.provider_id, r.endpoint_path,
       r.api_key_id, r.model, r.upstream_model, r.input_tokens, r.cache_read_tokens, r.output_tokens,
       r.cache_write_tokens, r.cache_write_1h_tokens, r.status_code, r.error_message, r.ttft_ms, r.time_spent_ms,
       r.created_at,
       r.model_cost, r.model_cost_currency,
       r.user_message_preview, r.project_id
FROM request r, anchor
WHERE r.span_id = anchor.span_id
ORDER BY r.created_at ASC, r.id ASC
`

type ListRequestsBySpanParams struct {
	ID          string           `json:"id"`
	IDCreatedAt pgtype.Timestamp `json:"idCreatedAt"`
}

type ListRequestsBySpanRow struct {
	ID                 string           `json:"id"`
	SpanID             pgtype.Text      `json:"spanId"`
	ParentSpanID       pgtype.Text      `json:"parentSpanId"`
	Type               int32            `json:"type"`
	Status             int32            `json:"status"`
	ProviderID         pgtype.Int4      `json:"providerId"`
	EndpointPath       pgtype.Text      `json:"endpointPath"`
	ApiKeyID           pgtype.Int4      `json:"apiKeyId"`
	Model              pgtype.Text      `json:"model"`
	UpstreamModel      pgtype.Text      `json:"upstreamModel"`
	InputTokens        pgtype.Int4      `json:"inputTokens"`
	CacheReadTokens    pgtype.Int4      `json:"cacheReadTokens"`
	OutputTokens       pgtype.Int4      `json:"outputTokens"`
	CacheWriteTokens   pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens pgtype.Int4      `json:"cacheWrite1hTokens"`
	StatusCode         pgtype.Int4      `json:"statusCode"`
	ErrorMessage       pgtype.Text      `json:"errorMessage"`
	TtftMs             pgtype.Int4      `json:"ttftMs"`
	TimeSpentMs        pgtype.Int4      `json:"timeSpentMs"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	ModelCost          pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency  pgtype.Text      `json:"modelCostCurrency"`
	UserMessagePreview pgtype.Text      `json:"userMessagePreview"`
	ProjectID          pgtype.Int4      `json:"projectId"`
}

func (q *Queries) ListRequestsBySpan(ctx context.Context, arg ListRequestsBySpanParams) ([]ListRequestsBySpanRow, error) {
	rows, err := q.db.Query(ctx, listRequestsBySpan, arg.ID, arg.IDCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsBySpanRow
	for rows.Next() {
		var i ListRequestsBySpanRow
		if err := rows.Scan(
			&i.ID,
			&i.SpanID,
			&i.ParentSpanID,
			&i.Type,
			&i.Status,
			&i.ProviderID,
			&i.EndpointPath,
			&i.ApiKeyID,
			&i.Model,
			&i.UpstreamModel,
			&i.InputTokens,
			&i.CacheReadTokens,
			&i.OutputTokens,
			&i.CacheWriteTokens,
			&i.CacheWrite1hTokens,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.TtftMs,
			&i.TimeSpentMs,
			&i.CreatedAt,
			&i.ModelCost,
			&i.ModelCostCurrency,
			&i.UserMessagePreview,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestMetrics = `-- name: UpdateRequestMetrics :exec
UPDATE request
SET ttft_ms = $2, input_tokens = $3, output_tokens = $4,
    cache_read_tokens = $5, cache_write_tokens = $6, cache_write_1h_tokens = $7
WHERE id = $1 AND created_at = $8::timestamp
`

type UpdateRequestMetricsParams struct {
	ID                 string           `json:"id"`
	TtftMs             pgtype.Int4      `json:"ttftMs"`
	InputTokens        pgtype.Int4      `json:"inputTokens"`
	OutputTokens       pgtype.Int4      `json:"outputTokens"`
	CacheReadTokens    pgtype.Int4      `json:"cacheReadTokens"`
	CacheWriteTokens   pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens pgtype.Int4      `json:"cacheWrite1hTokens"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) UpdateRequestMetrics(ctx context.Context, arg UpdateRequestMetricsParams) error {
	_, err := q.db.Exec(ctx, updateRequestMetrics,
		arg.ID,
		arg.TtftMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.CacheWrite1hTokens,
		arg.CreatedAt,
	)
	return err
}

const updateRequestModel = `-- name: UpdateRequestModel :exec
UPDATE request SET model = $2 WHERE id = $1 AND created_at = $3::timestamp
`

type UpdateRequestModelParams struct {
	ID        string           `json:"id"`
	Model     pgtype.Text      `json:"model"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) UpdateRequestModel(ctx context.Context, arg UpdateRequestModelParams) error {
	_, err := q.db.Exec(ctx, updateRequestModel, arg.ID, arg.Model, arg.CreatedAt)
	return err
}

const updateRequestOnComplete = `-- name: UpdateRequestOnComplete :exec
UPDATE request
SET status_code = $2, error_message = $3, time_spent_ms = $4, status = $5,
    ttft_ms = $6, input_tokens = $7, output_tokens = $8,
    cache_read_tokens = $9, cache_write_tokens = $10,
    cache_write_1h_tokens = $11,
    model_cost = $12, model_cost_currency = $13
WHERE id = $1 AND created_at = $14::timestamp
`

type UpdateRequestOnCompleteParams struct {
	ID                 string           `json:"id"`
	StatusCode         pgtype.Int4      `json:"statusCode"`
	ErrorMessage       pgtype.Text      `json:"errorMessage"`
	TimeSpentMs        pgtype.Int4      `json:"timeSpentMs"`
	Status             int32            `json:"status"`
	TtftMs             pgtype.Int4      `json:"ttftMs"`
	InputTokens        pgtype.Int4      `json:"inputTokens"`
	OutputTokens       pgtype.Int4      `json:"outputTokens"`
	CacheReadTokens    pgtype.Int4      `json:"cacheReadTokens"`
	CacheWriteTokens   pgtype.Int4      `json:"cacheWriteTokens"`
	CacheWrite1hTokens pgtype.Int4      `json:"cacheWrite1hTokens"`
	ModelCost          pgtype.Numeric   `json:"modelCost"`
	ModelCostCurrency  pgtype.Text      `json:"modelCostCurrency"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) UpdateRequestOnComplete(ctx context.Context, arg UpdateRequestOnCompleteParams) error {
	_, err := q.db.Exec(ctx, updateRequestOnComplete,
		arg.ID,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.TimeSpentMs,
		arg.Status,
		arg.TtftMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.CacheWrite1hTokens,
		arg.ModelCost,
		arg.ModelCostCurrency,
		arg.CreatedAt,
	)
	return err
}

const updateRequestOnHeader = `-- name: UpdateRequestOnHeader :exec
UPDATE request
SET provider_id = $2, model = $3, upstream_model = $4, endpoint_path = $5, api_key_id = $6, status = $7
WHERE id = $1 AND created_at = $8::timestamp
`

type UpdateRequestOnHeaderParams struct {
	ID            string           `json:"id"`
	ProviderID    pgtype.Int4      `json:"providerId"`
	Model         pgtype.Text      `json:"model"`
	UpstreamModel pgtype.Text      `json:"upstreamModel"`
	EndpointPath  pgtype.Text      `json:"endpointPath"`
	ApiKeyID      pgtype.Int4      `json:"apiKeyId"`
	Status        int32            `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) UpdateRequestOnHeader(ctx context.Context, arg UpdateRequestOnHeaderParams) error {
	_, err := q.db.Exec(ctx, updateRequestOnHeader,
		arg.ID,
		arg.ProviderID,
		arg.Model,
		arg.UpstreamModel,
		arg.EndpointPath,
		arg.ApiKeyID,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const updateRequestProjectID = `-- name: UpdateRequestProjectID :exec
UPDATE request SET project_id = $2
WHERE id = $1 AND created_at = $3::timestamp
`

type UpdateRequestProjectIDParams struct {
	ID        string           `json:"id"`
	ProjectID pgtype.Int4      `json:"projectId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

// Backfills the meta request row's project_id after authentication completes.
// The meta InsertRequest fires before auth so audit rows always exist; the
// account-scoped project resolution then writes the matched id here.
func (q *Queries) UpdateRequestProjectID(ctx context.Context, arg UpdateRequestProjectIDParams) error {
	_, err := q.db.Exec(ctx, updateRequestProjectID, arg.ID, arg.ProjectID, arg.CreatedAt)
	return err
}
